import Head from 'next/head';
import Image from 'next/image';
import { Header } from "@/components/Header";
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>BlogTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full max-w-[1120px] flex flex-col mx-auto pb-12 px-4">
        <Header />

        <Link
        href="/post"
        className="w-full h-full flex gap-4 lg:gap-8 flex-col sm:flex-row items-center justify-center mt-12 hover:brightness-75 transition-all">
          <div className="flex flex-1 w-full h-full min-h [240px] md:min-h-[334px] relative rounded-2xl overFlow-hidden">
            <Image
              src="https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Nagi"
              fill={true}
              style={{
                objectFit: "cover",
                borderRadius: "50px"
              }}
            />
          </div>

          <div className="flex flex-1 h-full flex-col gap-3 lg:gap-6">
            <h1 className="font-bold text-3xl md:text-[40px] text-blue-600">Como desevolver um blog com Next.js</h1>
            <p className="text-zinc-600 text-sm md:text-base text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolore consequuntur, eligendi ipsam possimus voluptatum molestiae culpa omnis aperiam facilis officiis! Temporibus illo recusandae quisquam quas facilis architecto corrupti praesentium dolores.</p>

            <div>
              <p className="font-bold text-zinc-900">Nagi Itoshi</p>
              <p className="text-zinc-600 text-sm">31 de janeiro de 2025</p>
            </div>
          </div>
        </Link>
        <div className='flex flex-col items-center sm:grid grid-cols-2 md:grid-cols-3 gap-4 lg:gap-8 mt-12'>
          

        </div>
        <div></div>

      </div>
    </>
  )
}

